# file generated by setuptools_scm
# don't change, don't track in version control
TYPE_CHECKING = False
if TYPE_CHECKING:
    pass

__version__ = version = "1.0.1.dev1+ge477237.d20230924"  # type: str
__version_tuple__ = version_tuple = (1, 0, 1, "dev1", "ge477237.d20230924")  # type: Tuple[int | str, ...]
