name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  test:
    uses: sscovil/python-dev-cli/.github/workflows/test.yml@main

  publish:
    if: github.repository == 'sscovil/python-dev-cli'
    needs: [test]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/sscovil/python-dev-cli
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Build package
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[publish]"
          python -m build --sdist --wheel .
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true  # Skip upload if package with same version already exists
          verbose: true  # Print a lot of debugging information, for troubleshooting
