name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  test:
    uses: sscovil/python-dev-cli/.github/workflows/test.yml@main
  publish:
    if: github.repository == 'sscovil/python-dev-cli'
    needs: [test]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/sscovil/python-dev-cli
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v3
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
