name: Build & Test

on:
  push:
  workflow_dispatch:  # Allows manually triggering this workflow from the Actions tab
  workflow_call:  # Allows other workflows to trigger this workflow

jobs:
  test:
    if: github.repository == 'sscovil/python-dev-cli'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: ["3.11", "3.12.0-rc.3"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[dev]"
      - name: Run tests
        run: |
          dev lint
          dev test
